// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcg0Hy70lCRpwslatPj5uS4f_5Rt_V2U',
    appId: '1:559036193887:web:a771771489d1bf84300fea',
    messagingSenderId: '559036193887',
    projectId: 'btechshayak',
    authDomain: 'btechshayak.firebaseapp.com',
    storageBucket: 'btechshayak.appspot.com',
    measurementId: 'G-GXGPG01RWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqlCWjvoztp0OKeqEjf6s5LuBPjMNUnlo',
    appId: '1:559036193887:android:54f5c79350350b9a300fea',
    messagingSenderId: '559036193887',
    projectId: 'btechshayak',
    storageBucket: 'btechshayak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQvsbKtJsDzXKsCokUlYixZePk_ZBu2g',
    appId: '1:559036193887:ios:8e561747f01fac6b300fea',
    messagingSenderId: '559036193887',
    projectId: 'btechshayak',
    storageBucket: 'btechshayak.appspot.com',
    iosBundleId: 'com.example.btechshayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUQvsbKtJsDzXKsCokUlYixZePk_ZBu2g',
    appId: '1:559036193887:ios:9c6dd6ee3624cb50300fea',
    messagingSenderId: '559036193887',
    projectId: 'btechshayak',
    storageBucket: 'btechshayak.appspot.com',
    iosBundleId: 'com.example.btechshayak.RunnerTests',
  );
}
